services:
  - type: web
    name: chat-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "daphne chat_system.asgi:application --port $PORT --bind 0.0.0.0"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: chat_system.settings
